<!-- 
~ Copyright 2018, 2019, 2020 Uppsala University Library 
~ 
~ This file is part of Cora. 
~ 
~ 	Cora is free software: you can redistribute it and/or modify 
~ 	it under the terms of the GNU General Public License as published by 
~ 	the Free Software Foundation, either version 3 of the License, or 
~ 	(at your option) any later version. 
~ 
~ 	Cora is distributed in the hope that it will be useful, 
~ 	but WITHOUT ANY WARRANTY; without even the implied warranty of 
~ 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
~ 	GNU General Public License for more details. 
~ 
~ 	You should have received a copy of the GNU General Public License 
~ 	along with Cora. If not, see <http://www.gnu.org/licenses />. 
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>se.uu.ub.cora</groupId>
		<artifactId>cora-parent</artifactId>
		<version>3.2.0</version>
	</parent>

	<artifactId>urnnbn</artifactId>
	<version>0.2.1-SNAPSHOT</version>
	<packaging>war</packaging>

	<name>Cora URN-NBN</name>
	<build>
		<finalName>urnnbn</finalName>
	</build>
	
	<properties>
		<coralog4j.version>2.16.0</coralog4j.version>
		<logger.version>2.10.0</logger.version>
		<logger-spies.version>1.5.0</logger-spies.version>
		<servlet-api.version>6.1.0</servlet-api.version>
		<jersey.version>4.0.2</jersey.version>
		<initialize.version>1.8.0</initialize.version>
		<initialize-spies.version>1.7.0</initialize-spies.version>
		<sqldatabase.version>7.9.0</sqldatabase.version>
		<testutils.version>1.14.0</testutils.version>
		
	</properties>

	<scm>
		<connection>scm:git:https://github.com/lsu-ub-uu/cora-urnnbn.git</connection>
		<developerConnection>scm:git:https://github.com/lsu-ub-uu/cora-urnnbn.git</developerConnection>
		<url>https://github.com/lsu-ub-uu/cora-urnnbn.git</url>
    <tag>release/0.2</tag>
  </scm>

	<dependencies>
		<dependency>
			<groupId>se.uu.ub.cora</groupId>
			<artifactId>log4j</artifactId>
			<version>${coralog4j.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>se.uu.ub.cora</groupId>
			<artifactId>logger-spies</artifactId>
			<version>${logger-spies.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>se.uu.ub.cora</groupId>
			<artifactId>logger</artifactId>
			<version>${logger.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.containers</groupId>
			<artifactId>jersey-container-servlet</artifactId>
			<version>${jersey.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-multipart</artifactId>
			<version>${jersey.version}</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-common</artifactId>
			<version>${jersey.version}</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.inject</groupId>
			<artifactId>jersey-hk2</artifactId>
			<version>${jersey.version}</version>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>${servlet-api.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>se.uu.ub.cora</groupId>
			<artifactId>initialize</artifactId>
			<version>${initialize.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>${servlet-api.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>se.uu.ub.cora</groupId>
			<artifactId>initialize</artifactId>
			<version>${initialize.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>se.uu.ub.cora</groupId>
			<artifactId>sqldatabase</artifactId>
			<version>${sqldatabase.version}</version>
		</dependency>
		<dependency>
			<groupId>se.uu.ub.cora</groupId>
			<artifactId>testutils</artifactId>
			<version>${testutils.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>se.uu.ub.cora</groupId>
			<artifactId>initialize-spies</artifactId>
			<version>${initialize-spies.version}</version>
			<scope>test</scope>
		</dependency>
				
	</dependencies>
</project>